#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
#
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 311291-web-01 100.26.247.60 check
    server 311291-web-02 100.25.29.45 check
"
# Update packages
sudo apt-get -y update
sudo apt-get -y upgrade
#install HAPROXY
sudo apt-get -y install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
